CMPUT301F19T02/Vybe

- doc/Team.txt
> Add Personal Entry

- app/src/main/java/com/example/vybe/MyVibesActivity.java
- app/src/main/java/com/example/vybe/VibeEvent.java
Testing adding to firestore
Added method to VibeEvent to add a vibe event to Firestore. Also hardcoded some tests to make sure it was displayed in the ListView from Firestore
Closes # 63  
N/A
> Add Vibe Event to Firestore

- app/src/main/java/com/example/vybe/VibeEvent.java
Remove code that caused app to crash. The following code snippet should be addressed and added back under issue #81 
```java
public void addVibe(VibeEvent vb, CollectionReference cr){
HashMap<String, Object> data = new HashMap<>();
long seconds = vb.getDateTime().atZone(ZoneId.systemDefault()).toInstant().toEpochMilli();
Date date = new Date(seconds);
data.put("vibe", "whatever");
data.put("datetime", date);
data.put("reason", vb.getReason());
data.put("socSit", vb.getSocialSituation());
cr.document("event").set(data);
}
```
> fix crash and remove misplaced adding event to database code

- app/src/main/java/com/example/vybe/ViewVibeActivity.java
- app/src/main/res/layout/activity_view_vibe.xml
Displayed date, time, reason (if there is one), social situation (if there is one) in View Vibe activity.
The star is a placeholder for the emoticon
> view vibe almost done

- app/src/main/java/com/example/vybe/MyVibesActivity.java
Added query to sort the mood history by datetime descending
Closes # 48
N/A
> Sort History by Descending Date

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/vybe/AddEditVibeActivity.java
- app/src/main/java/com/example/vybe/MyVibesActivity.java
- app/src/main/java/com/example/vybe/VibeEvent.java
- app/src/main/res/layout/activity_add_edit_vibe.xml
Can add a photo to a mood event. It will be stored in the Firebase Storage system under the "reasons" folder.
Closes #40 
> 40.add photo to mood event

- app/src/main/java/com/example/vybe/AddEditVibeActivity.java
- app/src/main/java/com/example/vybe/MainActivity.java
- app/src/main/java/com/example/vybe/MyVibesActivity.java
- app/src/main/java/com/example/vybe/MyVibesAdapter.java
- app/src/main/java/com/example/vybe/VibeEvent.java
- app/src/main/java/com/example/vybe/VibeFactory.java
- app/src/main/java/com/example/vybe/ViewVibeActivity.java
- app/src/main/java/com/example/vybe/vibefactory/AngryVibe.java
- app/src/main/java/com/example/vybe/vibefactory/DisgustedVibe.java
- app/src/main/java/com/example/vybe/vibefactory/HappyVibe.java
- app/src/main/java/com/example/vybe/vibefactory/SadVibe.java
- app/src/main/java/com/example/vybe/vibefactory/ScaredVibe.java
- app/src/main/java/com/example/vybe/vibefactory/SurprisedVibe.java
- app/src/main/java/com/example/vybe/vibefactory/Vibe.java
Added Javadocs and comments to various files
> 94.add javadocs

- app/src/main/java/com/example/vybe/VibeEvent.java
- app/src/test/java/com/example/vybe/VibeEventTest.java
- app/src/test/java/com/example/vybe/VibeFactoryTest.java
Added and modified/fixed various unit tests. See Issue #80 for more details
> 80.code base tests

- app/src/androidTest/java/com/example/vybe/AddEditVibeActivityTest.java
- app/src/main/java/com/example/vybe/AddEditVibeActivity.java
- app/src/main/java/com/example/vybe/util/Constants.java
Description: Fix bug where user may enter more than 3 words in reason editText field
Closes #109
Checklist
> 109.event reason word limit

- app/build.gradle
- app/src/main/java/com/example/vybe/AddEditVibeActivity.java
- app/src/main/java/com/example/vybe/MyVibesAdapter.java
- app/src/main/java/com/example/vybe/VibeCarouselFragment.java
- app/src/main/java/com/example/vybe/VibeEvent.java
- app/src/main/java/com/example/vybe/VibeFactory.java
- app/src/main/java/com/example/vybe/ViewVibeActivity.java
- app/src/main/res/drawable/ic_no_vibe.xml
- app/src/main/res/drawable/ic_sad.xml
- app/src/main/res/drawable/ic_scared.xml
- app/src/main/res/layout/activity_add_edit_vibe.xml
- app/src/main/res/layout/fragment_vibe_carousel.xml
- app/src/main/res/values/colors.xml
- build.gradle
- docs/UML/uml.plantuml
Description: Made custom vibe selector instead of dropdown. Changed the vector assets for Sad and Scared emoticons Refer to Issue #88 
Checklist
> 88.implement custom vibe selector

- app/build.gradle
- app/src/main/java/com/example/vybe/AddEditVibeActivity.java
- app/src/main/java/com/example/vybe/ViewVibeActivity.java
- app/src/main/res/layout/activity_view_vibe.xml
Description: 
- Display image when viewing/editing a VibeEvent
Closes #97   
Checklist
> 97.edit and view photo for vibe event

- app/src/main/java/com/example/vybe/AddEditVibeActivity.java
- app/src/main/java/com/example/vybe/LocationSelectionDialog.java
- app/src/main/java/com/example/vybe/MapFragment.java
- app/src/main/java/com/example/vybe/MapViewActivity.java
- app/src/main/res/layout/activity_add_edit_vibe.xml
- app/src/main/res/layout/activity_map_view.xml
> map view is now in add/edit vibeevent and zooms to location

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/vybe/MyVibesActivity.java
- app/src/main/java/com/example/vybe/ProfileAdapter.java
- app/src/main/java/com/example/vybe/SearchProfilesActivity.java
- app/src/main/java/com/example/vybe/SocialActivity.java
- app/src/main/res/layout/activity_search_profiles.xml
- app/src/main/res/layout/activity_social.xml
- app/src/main/res/layout/user_item.xml
- app/src/main/res/values/strings.xml
Description: 
Created the following files:
- SearchProfilesActivity
- SocialActivity
- ProfileAdapter
- activity_search_profiles
- activity_social
- user_item
Users should now be able to search for other users stored in the database. Username of the person who is logged in also shows up in the searched list, but can just show own profile when selected.
When searching for a user, any person with a username that contains the entered string should return (e.g. "white" should return "bluevibeswhitedragon" "whiteman", etc.) …
> 50.search for other users

- app/src/main/java/com/example/vybe/MyVibesActivity.java
- app/src/main/java/com/example/vybe/User.java
- app/src/main/java/com/example/vybe/ViewProfileActivity.java
- app/src/main/res/layout/activity_view_profile.xml
Description: 
Created the Profile page. It contains username, email and a logout button.
May need to hide the logout button if the bundled User's email does not match the logged-in user's email.
Also implemented a logout button so we can test logging out.
Closes #42  
Checklist
> 42.create user profile page

- app/src/main/res/layout/activity_add_edit_vibe.xml
Description: 
Removed commented out TextView in add_edit_activity's xml
> Removed commented out TextView in add_edit_activity's xml

- app/src/main/java/com/example/vybe/AddEdit/AddEditVibeEventActivity.java
- app/src/main/java/com/example/vybe/CreateAccountActivity.java
- app/src/main/java/com/example/vybe/MainActivity.java
- app/src/main/java/com/example/vybe/MyVibesActivity.java
Description: 
Updated the Firestore queries with the new structure to have the Users collection contain the VibeEvent information under the logged-in user.
I will need to clean up the Database and delete all the current users that have been created as they no longer follow the new structure
Closes #124   
Checklist
[//]: # (Add an x between …
> Updated DB queries

- app/src/main/java/com/example/vybe/AddEdit/AddEditVibeEventActivity.java
- app/src/main/java/com/example/vybe/MapFragment.java
- app/src/main/java/com/example/vybe/Models/VibeEvent.java
- app/src/main/java/com/example/vybe/MyVibesActivity.java
- app/src/main/java/com/example/vybe/ViewVibeActivity.java
- app/src/main/res/layout/activity_view_vibe.xml
> 126.add map to view

- app/src/main/java/com/example/vybe/MyVibesAdapter.java
- app/src/main/java/com/example/vybe/SearchProfilesActivity.java
- app/src/main/java/com/example/vybe/ViewProfileActivity.java
- app/src/main/res/layout/activity_view_profile.xml
- app/src/main/res/layout/my_vibe_item.xml
- app/src/main/res/values/strings.xml
Description: Modified the ViewProfileActivity to show a 'Send Request' button if user is viewing other people's profiles. Also changed the MyVibesAdapter to view the vibe name instead of the reason
Closes #45 
Checklist
> 45.view other user profile

- app/src/main/java/com/example/vybe/Models/User.java
- app/src/main/java/com/example/vybe/SearchProfilesActivity.java
- app/src/main/java/com/example/vybe/ViewProfileActivity.java
Description: 
- Modified `User` Model class to store user ID and a list of users who send a follow request that is also stored on Firestore. I believe each user ID is unique on Firestore too, so that works out well. The added getters, setters, and more wrapper classes as well. 
- `OnClick` for the `Send Follow Request` button, the current user will create a document in a `Requests` collection that is a sub collection for another user that will have the same name as their own user ID. I changed some of the TextViews to show this below to test. TextViews should be back to normal now.
- After consideration that we actually need to query for our own username, it is possible we might be better off storing …
> 51.Sending Follow Requests

- app/src/main/java/com/example/vybe/MyVibesActivity.java
- app/src/main/java/com/example/vybe/MyVibesAdapter.java
- app/src/main/java/com/example/vybe/SwipeItemTouchHelper.java
- app/src/main/res/drawable/ic_title_vibe_alt.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_my_vibes.xml
- app/src/main/res/values/colors.xml
Description: Removed alertdialog and added swipe functionality for edit and delete vibe event. To make this work, the listview was also converted to a recyclerview, which involves having to rewrite the MyVibesAdapter class
Closes #133 
Checklist
> 133.fix alert dialog edit delete

- app/src/androidTest/java/com/example/vybe/MainActivityTest.java
Description: After some talk with @raysarinas , I think we agreed that having a branch dedicated to just testing would lead to issues down the road when considering multiple different testing issues. The new and final plan for testing is to just stick to the current process of making issues for writing tests. If people are okay with this, I'll get started on testing!
> Merge Testing branch back into master

- app/src/main/res/layout/activity_view_vibe.xml
- app/src/test/java/com/example/vybe/UserTest.java
- app/src/test/java/com/example/vybe/VibeEventTest.java
- app/src/test/java/com/example/vybe/VibeFactoryTest.java
Description: 
Updated Model class tests to have documentation and more up to date tests. I did not make a separate test file for the SocialSituation enumeration class because I was not sure how to test that and will probably update the current social situation tests to reflect changes down the road.
JavaDocs have also been added to the top of the test classes.
I also was not sure how to properly test any of the dateTime methods in the VibeEvent classes as it lead to many different errors.
[//]: # (automatically closes …
> Update Unit Tests for Model Classes

- app/src/main/java/com/example/vybe/AddEdit/LocationSelectionDialog.java
- app/src/main/java/com/example/vybe/MapViewActivity.java
- app/src/main/java/com/example/vybe/SocialActivity.java
refer to commits to see what was added
also i added a bias to the location selector
> 59.implement follower map

- app/build.gradle
- app/src/test/java/com/example/vybe/VibeEventTest.java
Description: Fixes the mock dependency problem being faced in the issue closed below
* Unit tests are updated to properly test to verify a vibe's date in a vibe event object
* Updated apps gradle file to have `testOptions`
* Ran the app and all tests and had no issues
Closes #169 
Checklist
[//]: # (Add an x between square brackets to mark …
> update unit tests and apply mock dependency fix in gradle

- app/src/main/java/com/example/vybe/MyVibesActivity.java
Description: There still needs to be more but just in case, here is the MVP refactoring for the filter list I guess
Closes #(issue)  
Checklist
> mvp refactoring of filter list

- app/src/main/java/com/example/vybe/Models/User.java
- app/src/main/java/com/example/vybe/MyRequestsActivity.java
- app/src/main/java/com/example/vybe/ViewProfileActivity.java
Description: See Issue #172. ~~This will require complete overhaul of everything stored in Firebase, but I will do that sometime in the middle of the night to make sure it causes no issues and no one is working on it~~ Requests just won't be displayed on any of the current users.
Closes #172 
Checklist
[//]: # (Add an x between square brackets …
> 172.refactor request list

- app/src/main/AndroidManifest.xml
Description: See Issue #127 
Closes #127
> screen lock protocol initiated

- app/src/main/java/com/example/vybe/AddEdit/AddEditVibeEventActivity.java
- app/src/main/java/com/example/vybe/CustomScrollView.java
- app/src/main/java/com/example/vybe/LocationController.java
- app/src/main/java/com/example/vybe/MapFragment.java
- app/src/main/java/com/example/vybe/MapViewActivity.java
- app/src/main/res/drawable/ic_map_marker_vibe.xml
Description: #186 . Update some documentation and overlay map markers to use a Canvas to show the emoticons on top of a black marker. Otherwise when picking a location, should still have the same purple color. 
Closes #186 
Checklist
> 186.change map marker color

- app/src/main/java/com/example/vybe/AddEdit/LocationSelectionDialog.java
- Improved Documentation
- added function for building autocomplete
- added catch case for null location
> Emmett location fix
